#!/usr/bin/env python
"""Patch i18n locales with residual PT strings from case/dl/walk routes."""
import json
from pathlib import Path

i18n_dir = Path(r"C:\Users\rafaa\Documents\GitHub\presuntinho\src\lib\i18n")

new_keys = {
    # case — OVERVIEW value column (right-side cell)
    "case.overview.empresa.value":     {"pt-PT": "Equivalenza S.L.",          "en": "Equivalenza S.L.",          "fr": "Equivalenza S.L.",          "tn": "Equivalenza S.L.",          "ar": "Equivalenza S.L."},
    "case.overview.fundada.value":     {"pt-PT": "Barcelona, Espanha, 2011", "en": "Barcelona, Spain, 2011",    "fr": "Barcelone, Espagne, 2011",   "tn": "Barcelone, Espagne, 2011",   "ar": "برشلونة، إسبانيا، 2011"},
    "case.overview.categoria.value":   {"pt-PT": "Fragrâncias affordable / dupe retail", "en": "Affordable fragrances / dupe retail", "fr": "Parfums abordables / dupe retail", "tn": "Parfums abordables / dupe retail", "ar": "عطور بأسعار معقولة / بيع مقلّد"},
    "case.overview.modelo.value":      {"pt-PT": "Rede de franchising + e-commerce", "en": "Franchise network + e-commerce", "fr": "Réseau de franchise + e-commerce", "tn": "Réseau franchise + e-commerce", "ar": "شبكة امتياز + تجارة إلكترونية"},
    "case.overview.ceo.value":         {"pt-PT": "Juan Franco (nomeado em 2023)", "en": "Juan Franco (appointed 2023)", "fr": "Juan Franco (nommé en 2023)", "tn": "Juan Franco (nommé en 2023)", "ar": "خوان فرانكو (مُعيَّن 2023)"},
    "case.overview.ebitda.value":      {"pt-PT": "€2M → Objetivo €8M",       "en": "€2M → Target €8M",            "fr": "2M € → Objectif 8M €",       "tn": "2M € → Objectif 8M €",       "ar": "٢ مليون € → هدف ٨ مليون €"},

    # case — FORCES
    "case.forces.1.title": {"pt-PT": "1. Colapso do segmento dupe", "en": "1. Dupe segment collapse", "fr": "1. Effondrement du segment dupe", "tn": "1. Effondrement du segment dupe", "ar": "١. انهيار قطاع المقلّد"},
    "case.forces.1.text":  {"pt-PT": "O segmento espanhol de dupes caiu de 37% para 13% dos consumidores entre 2018 e 2023 — uma queda de 65% no mercado core da Equivalenza.", "en": "Spain's dupe segment fell from 37% to 13% of consumers between 2018 and 2023 — a 65% drop in Equivalenza's core market.", "fr": "Le segment espagnol dupe est passé de 37% à 13% des consommateurs entre 2018 et 2023 — une baisse de 65% sur le marché principal d'Equivalenza.", "tn": "Le segment dupe espagnol est passé de 37% à 13% des consommateurs entre 2018 et 2023 — une baisse de 65% sur le marché principal d'Equivalenza.", "ar": "انخفض قطاع المقلّد الإسباني من ٣٧٪ إلى ١٣٪ من المستهلكين بين ٢٠١٨ و٢٠٢٣ — انخفاض ٦٥٪ في سوق إيكويفالينزا الأساسي."},
    "case.forces.2.title": {"pt-PT": "2. Efeito sanduíche",          "en": "2. Sandwich effect",          "fr": "2. Effet sandwich",          "tn": "2. Effet sandwich",          "ar": "٢. تأثير الشطيرة"},
    "case.forces.2.text":  {"pt-PT": "Marcas premium a descontarem por cima (mais acessíveis). Zara e Mercadona a melhorar por baixo (mais aspiracionais). Equivalenza espremida no meio.", "en": "Premium brands discounting from above (more accessible). Zara and Mercadona upgrading from below (more aspirational). Equivalenza squeezed in the middle.", "fr": "Les marques premium qui se discountent par le haut (plus accessibles). Zara et Mercadona qui montent en gamme par le bas (plus aspirationnelles). Equivalenza coincée au milieu.", "tn": "Les marques premium qui se discountent par le haut (plus accessibles). Zara et Mercadona qui montent en gamme par le bas (plus aspirationnelles). Equivalenza coincée au milieu.", "ar": "العلامات التجارية الفاخرة تخصم من الأعلى (أكثر سهولة). زارا وميركادونا ترتقيان من الأسفل (أكثر طموحاً). إيكويفالينزا محصورة في الوسط."},
    "case.forces.3.title": {"pt-PT": "3. Competidores digitais nativos", "en": "3. Digital-native competitors", "fr": "3. Concurrents natifs numériques", "tn": "3. Concurrents natifs numériques", "ar": "٣. المنافسون الرقميون الأصليون"},
    "case.forces.3.text":  {"pt-PT": "Divain, Dossier, Adopt — operam sem custos físicos e investem mais em marketing por cada euro de receita.", "en": "Divain, Dossier, Adopt — operate without physical costs and invest more in marketing per euro of revenue.", "fr": "Divain, Dossier, Adopt — opèrent sans coûts physiques et investissent davantage en marketing par euro de chiffre d'affaires.", "tn": "Divain, Dossier, Adopt — opèrent sans coûts physiques et investissent davantage en marketing par euro de chiffre d'affaires.", "ar": "ديفين، دوسييه، أدوبت — تعمل بدون تكاليف مادية وتستثمر أكثر في التسويق لكل يورو من الإيرادات."},

    # dl
    "dl.card.pdf.title":        {"pt-PT": "Assignment PDF",         "en": "Assignment PDF",         "fr": "PDF du devoir",        "tn": "PDF du devoir",        "ar": "PDF الواجب"},
    "dl.card.pdf.desc":         {"pt-PT": "O mid-term completo — 13 páginas, ~2000 palavras, referências Harvard, capa, TOC, matriz TOWS com código de cores, anexo com tabela de dados-chave e visual da buyer persona.", "en": "The full mid-term — 13 pages, ~2000 words, Harvard references, cover, TOC, color-coded TOWS matrix, annex with key-data table and buyer persona visual.", "fr": "Le mid-term complet — 13 pages, ~2000 mots, références Harvard, couverture, TOC, matrice TOWS codée par couleurs, annexe avec tableau des données clés et visuel de la buyer persona.", "tn": "Le mid-term complet — 13 pages, ~2000 mots, références Harvard, couverture, TOC, matrice TOWS codée par couleurs, annexe avec tableau des données clés et visuel de la buyer persona.", "ar": "الميد تيرم الكامل — ١٣ صفحة، ~٢٠٠٠ كلمة، مراجع هارفارد، غلاف، جدول محتويات، مصفوفة TOWS ملوّنة، ملحق بجدول البيانات الأساسية ومرئي buyer persona."},
    "dl.card.docx.title":       {"pt-PT": "Versão Word editável",     "en": "Editable Word version",  "fr": "Version Word éditable", "tn": "Version Word éditable", "ar": "نسخة Word قابلة للتعديل"},
    "dl.card.docx.desc":        {"pt-PT": "Mesmo conteúdo do PDF, editável. Usa este para reescreveres na tua voz antes de submeter.", "en": "Same content as the PDF, editable. Use this to rewrite in your own voice before submitting.", "fr": "Même contenu que le PDF, éditable. Utilise cette version pour réécrire dans ta voix avant de soumettre.", "tn": "Même contenu que le PDF, éditable. Utilise cette version pour réécrire dans ta voix avant de soumettre.", "ar": "نفس محتوى PDF، قابل للتعديل. استخدم هذا لإعادة الكتابة بأسلوبك قبل التسليم."},
    "dl.card.audio.title":      {"pt-PT": "Audio walkthroughs (5 MP3)", "en": "Audio walkthroughs (5 MP3)", "fr": "Guides audio (5 MP3)",  "tn": "Guides audio (5 MP3)",  "ar": "شروحات صوتية (5 MP3)"},
    "dl.card.audio.desc":       {"pt-PT": "Ouve enquanto revês. Voz em inglês (3 faixas) e versões de intro em inglês + PT.", "en": "Listen while you review. English voice (3 tracks) and intro versions in EN + PT.", "fr": "Écoute pendant que tu révises. Voix anglaise (3 pistes) et versions d'intro en EN + PT.", "tn": "Écoute pendant que tu révises. Voix anglaise (3 pistes) et versions d'intro en EN + PT.", "ar": "استمع أثناء المراجعة. صوت إنجليزي (3 مسارات) ونسخ المقدمة بالإنجليزية والبرتغالية."},
    "dl.extra.swot":            {"pt-PT": "🎧 Secções 1+2 (SWOT + Persona)",                "en": "🎧 Sections 1+2 (SWOT + Persona)",                "fr": "🎧 Sections 1+2 (SWOT + Persona)",                "tn": "🎧 Sections 1+2 (SWOT + Persona)",                "ar": "🎧 الأقسام ١+٢ (SWOT + بيرسونا)"},
    "dl.extra.persona":         {"pt-PT": "🎧 Secções 2+3 (Persona + Marketing Problem)",  "en": "🎧 Sections 2+3 (Persona + Marketing Problem)",  "fr": "🎧 Sections 2+3 (Persona + Problème marketing)",   "tn": "🎧 Sections 2+3 (Persona + Problème marketing)",   "ar": "🎧 الأقسام ٢+٣ (بيرسونا + مشكلة التسويق)"},
    "dl.extra.tows":            {"pt-PT": "🎧 Secções 4+5 (TOWS + Recommendation)",        "en": "🎧 Sections 4+5 (TOWS + Recommendation)",        "fr": "🎧 Sections 4+5 (TOWS + Recommandation)",         "tn": "🎧 Sections 4+5 (TOWS + Recommandation)",         "ar": "🎧 الأقسام ٤+٥ (TOWS + التوصية)"},
    "dl.extra.audioEn":         {"pt-PT": "🎧 Intro completa (EN)",                         "en": "🎧 Full intro (EN)",                              "fr": "🎧 Intro complète (EN)",                          "tn": "🎧 Intro complète (EN)",                          "ar": "🎧 المقدمة الكاملة (إنجليزي)"},
    "dl.extra.audioPt":         {"pt-PT": "🎧 Intro completa (PT)",                         "en": "🎧 Full intro (PT)",                              "fr": "🎧 Intro complète (PT)",                          "tn": "🎧 Intro complète (PT)",                          "ar": "🎧 المقدمة الكاملة (برتغالي)"},
    "dl.card.zip.title":        {"pt-PT": "ZIP de deliverables (V3)",                       "en": "Deliverables ZIP (V3)",                           "fr": "ZIP des livrables (V3)",                          "tn": "ZIP des livrables (V3)",                          "ar": "ملف ZIP للمخرجات (V3)"},
    "dl.card.zip.desc":         {"pt-PT": "Tudo o que estava no ZIP original do V3 — PDFs, DOCX, MP3s, persona visual.", "en": "Everything that was in the original V3 ZIP — PDFs, DOCX, MP3s, persona visual.", "fr": "Tout ce qui était dans le ZIP V3 original — PDF, DOCX, MP3, visuel de la persona.", "tn": "Tout ce qui était dans le ZIP V3 original — PDF, DOCX, MP3, visuel de la persona.", "ar": "كل ما كان في ملف V3 ZIP الأصلي — PDF وDOCX وMP3 ومرئي بيرسونا."},
    "dl.howto.h2":              {"pt-PT": "💡 Como usar o assignment",                      "en": "💡 How to use the assignment",                     "fr": "💡 Comment utiliser le devoir",                    "tn": "💡 Comment utiliser le devoir",                    "ar": "💡 كيفية استخدام الواجب"},
    "dl.howto.p1":              {"pt-PT": "<strong>NÃO submetas exatamente como está.</strong> O objetivo é leres, perceberes a análise, e reescreveres na tua voz. Muda os exemplos, reordena parágrafos, acrescenta a tua perspetiva.", "en": "<strong>Do NOT submit exactly as is.</strong> The goal is to read, understand the analysis, and rewrite in your own voice. Change the examples, reorder paragraphs, add your perspective.", "fr": "<strong>NE soumets PAS exactement tel quel.</strong> L'objectif est de lire, comprendre l'analyse, et réécrire dans ta voix. Change les exemples, réordonne les paragraphes, ajoute ta perspective.", "tn": "<strong>NE soumets PAS exactement tel quel.</strong> L'objectif est de lire, comprendre l'analyse, et réécrire dans ta voix. Change les exemples, réordonne les paragraphes, ajoute ta perspective.", "ar": "<strong>لا تقدّمه كما هو.</strong> الهدف هو أن تقرأ وتفهم التحليل وتعيد الكتابة بأسلوبك الخاص. غيّر الأمثلة وأعد ترتيب الفقرات وأضف منظورك."},
    "dl.howto.p2":              {"pt-PT": "Isto garante: (1) o texto soa a ti, (2) passa o Turnitin, (3) consegues defender cada ponto oralmente.", "en": "This ensures: (1) the text sounds like you, (2) it passes Turnitin, (3) you can defend each point orally.", "fr": "Cela garantit : (1) le texte te ressemble, (2) il passe Turnitin, (3) tu peux défendre chaque point à l'oral.", "tn": "Cela garantit : (1) le texte te ressemble, (2) il passe Turnitin, (3) tu peux défendre chaque point à l'oral.", "ar": "هذا يضمن: (١) النص يبدو وكأنك كتبته، (٢) يجتاز تيرنitin، (٣) تستطيع الدفاع عن كل نقطة شفهياً."},
    "dl.warning.h2":            {"pt-PT": "⚠️ Lembrete importante",                          "en": "⚠️ Important reminder",                            "fr": "⚠️ Rappel important",                              "tn": "⚠️ Rappel important",                              "ar": "⚠️ تذكير مهم"},
    "dl.warning.p":             {"pt-PT": "Q3 (Marketing Problem), Q4 (TOWS) e Q5 (Recommendation) <strong>não podem usar IA diretamente</strong>. Estas secções têm de ser inteiramente tuas. Usa este material para perceberes a metodologia e depois escreve sozinho/a.", "en": "Q3 (Marketing Problem), Q4 (TOWS) and Q5 (Recommendation) <strong>cannot use AI directly</strong>. These sections must be entirely yours. Use this material to understand the methodology and then write on your own.", "fr": "Q3 (Problème marketing), Q4 (TOWS) et Q5 (Recommandation) <strong>ne peuvent pas utiliser l'IA directement</strong>. Ces sections doivent être entièrement les tiennes. Utilise ce matériel pour comprendre la méthodologie puis écris seul(e).", "tn": "Q3 (Problème marketing), Q4 (TOWS) et Q5 (Recommandation) <strong>ne peuvent pas utiliser l'IA directement</strong>. Ces sections doivent être entièrement les tiennes. Utilise ce matériel pour comprendre la méthodologie puis écris seul(e).", "ar": "السؤال ٣ (مشكلة التسويق)، السؤال ٤ (TOWS) والسؤال ٥ (التوصية) <strong>لا يمكن استخدام الذكاء الاصطناعي فيها مباشرة</strong>. يجب أن تكون هذه الأقسام من كتابتك أنت بالكامل. استخدم هذا material لفهم المنهجية ثم اكتب بنفسك."},

    # walk — 5 steps + 3 audios
    "walk.step.swot.title":     {"pt-PT": "Análise SWOT",                "en": "SWOT Analysis",            "fr": "Analyse SWOT",            "tn": "Analyse SWOT",            "ar": "تحليل SWOT"},
    "walk.step.swot.what":      {"pt-PT": "SWOT da Equivalenza + 1 concorrente (Divain).", "en": "SWOT of Equivalenza + 1 competitor (Divain).", "fr": "SWOT d'Equivalenza + 1 concurrent (Divain).", "tn": "SWOT d'Equivalenza + 1 concurrent (Divain).", "ar": "SWOT لإيكويفالينزا + منافس واحد (ديفين)."},
    "walk.step.swot.how":       {"pt-PT": "4-5 bullets por quadrante. Cita o case study (Elson, 2024). Sê específica com números.", "en": "4-5 bullets per quadrant. Cite the case study (Elson, 2024). Be specific with numbers.", "fr": "4-5 puces par quadrant. Cite l'étude de cas (Elson, 2024). Sois précise avec les chiffres.", "tn": "4-5 puces par quadrant. Cite l'étude de cas (Elson, 2024). Sois précise avec les chiffres.", "ar": "٤-٥ نقاط في كل ربع. استشهد بدراسة الحالة (إلسون، ٢٠٢٤). كوني محددة بالأرقام."},
    "walk.step.swot.hint":      {"pt-PT": "NPS 17 vs Druni 56 é uma fraqueza que também serve de ponte para o Marketing Problem.", "en": "NPS 17 vs Druni 56 is a weakness that also serves as a bridge to the Marketing Problem.", "fr": "NPS 17 contre Druni 56 est une faiblesse qui sert aussi de pont vers le Problème marketing.", "tn": "NPS 17 contre Druni 56 est une faiblesse qui sert aussi de pont vers le Problème marketing.", "ar": "NPS ١٧ مقابل دروني ٥٦ هي نقطة ضعف تعمل أيضاً كجسر نحو مشكلة التسويق."},
    "walk.step.persona.title":  {"pt-PT": "Buyer Persona",               "en": "Buyer Persona",            "fr": "Buyer Persona",            "tn": "Buyer Persona",            "ar": "شخصية المشتري"},
    "walk.step.persona.what":   {"pt-PT": "Uma persona primária com demografia, psicografia, comportamento, frustrações.", "en": "One primary persona with demographics, psychographics, behaviour, frustrations.", "fr": "Une persona principale avec démographie, psychographie, comportement, frustrations.", "tn": "Une persona principale avec démographie, psychographie, comportement, frustrations.", "ar": "شخصية أساسية واحدة مع التركيبة السكانية والسيكوغرافية والسلوك والإحباطات."},
    "walk.step.persona.how":    {"pt-PT": "Ancorada em investigação do case study. Acrescenta um parágrafo de «Importância Estratégica» a explicar porque é que esta persona importa.", "en": "Anchored in case-study research. Add a «Strategic Importance» paragraph explaining why this persona matters.", "fr": "Ancrée dans la recherche de l'étude de cas. Ajoute un paragraphe « Importance stratégique » expliquant pourquoi cette persona compte.", "tn": "Ancrée dans la recherche de l'étude de cas. Ajoute un paragraphe « Importance stratégique » expliquant pourquoi cette persona compte.", "ar": "مرتكزة على بحث دراسة الحالة. أضف فقرة «الأهمية الاستراتيجية» توضح لماذا هذه الشخصية مهمة."},
    "walk.step.problem.title":  {"pt-PT": "Problema de Marketing",       "en": "Marketing Problem",        "fr": "Problème marketing",       "tn": "Problème marketing",       "ar": "مشكلة التسويق"},
    "walk.step.problem.what":   {"pt-PT": "Formula o problema mais urgente em SCQA.", "en": "Formulate the most urgent problem in SCQA.", "fr": "Formule le problème le plus urgent en SCQA.", "tn": "Formule le problème le plus urgent en SCQA.", "ar": "صُغي المشكلة الأكثر إلحاحاً في SCQA."},
    "walk.step.problem.how":    {"pt-PT": "Mostra o teu raciocínio. Termina com um problem statement claro (1-2 frases) que a recomendação vai resolver.", "en": "Show your reasoning. End with a clear problem statement (1-2 sentences) that the recommendation will solve.", "fr": "Montre ton raisonnement. Termine par un énoncé du problème clair (1-2 phrases) que la recommandation va résoudre.", "tn": "Montre ton raisonnement. Termine par un énoncé du problème clair (1-2 phrases) que la recommandation va résoudre.", "ar": "أظهِر تفكيرك. اختم ببيان مشكلة واضح (١-٢ جملة) ستحلّه التوصية."},
    "walk.step.tows.title":     {"pt-PT": "Matriz TOWS",                 "en": "TOWS Matrix",              "fr": "Matrice TOWS",              "tn": "Matrice TOWS",              "ar": "مصفوفة TOWS"},
    "walk.step.tows.what":      {"pt-PT": "Matriz 2×2. 4 alternativas estratégicas. Breve avaliação de cada uma.", "en": "2×2 matrix. 4 strategic alternatives. Brief evaluation of each.", "fr": "Matrice 2×2. 4 alternatives stratégiques. Brève évaluation de chacune.", "tn": "Matrice 2×2. 4 alternatives stratégiques. Brève évaluation de chacune.", "ar": "مصفوفة ٢×٢. ٤ بدائل استراتيجية. تقييم موجز لكل منها."},
    "walk.step.tows.how":       {"pt-PT": "Cada célula = 1 estratégia em 1 linha. Depois um parágrafo a explicar porque é que SO ganha (ou qualquer outra que escolhas).", "en": "Each cell = 1 strategy in 1 line. Then a paragraph explaining why SO wins (or whichever you pick).", "fr": "Chaque cellule = 1 stratégie en 1 ligne. Puis un paragraphe expliquant pourquoi SO gagne (ou celui que tu choisis).", "tn": "Chaque cellule = 1 stratégie en 1 ligne. Puis un paragraphe expliquant pourquoi SO gagne (ou celui que tu choisis).", "ar": "كل خلية = استراتيجية واحدة في سطر. ثم فقرة توضح لماذا SO تفوز (أو أي واحدة تختارين)."},
    "walk.step.rec.title":      {"pt-PT": "Recomendação Estratégica",    "en": "Strategic Recommendation", "fr": "Recommandation stratégique", "tn": "Recommandation stratégique", "ar": "التوصية الاستراتيجية"},
    "walk.step.rec.what":       {"pt-PT": "Escolhe uma estratégia TOWS e defende-a.", "en": "Pick one TOWS strategy and defend it.", "fr": "Choisis une stratégie TOWS et défends-la.", "tn": "Choisis une stratégie TOWS et défends-la.", "ar": "اختاري استراتيجية TOWS واحدة ودافعي عنها."},
    "walk.step.rec.how":        {"pt-PT": "Porque é que esta (e não as outras). Verificação de viabilidade. Plano de implementação com liderança, recursos, timeline.", "en": "Why this one (and not the others). Feasibility check. Implementation plan with leadership, resources, timeline.", "fr": "Pourquoi celle-ci (et pas les autres). Vérification de faisabilité. Plan d'implémentation avec leadership, ressources, calendrier.", "tn": "Pourquoi celle-ci (et pas les autres). Vérification de faisabilité. Plan d'implémentation avec leadership, ressources, calendrier.", "ar": "لماذا هذه (وليس غيرها). التحقق من الجدوى. خطة التنفيذ مع القيادة والموارد والجدول الزمني."},
    "walk.audio.swot.title":    {"pt-PT": "Secções 1 + 2",                "en": "Sections 1 + 2",            "fr": "Sections 1 + 2",            "tn": "Sections 1 + 2",            "ar": "الأقسام ١ + ٢"},
    "walk.audio.swot.label":    {"pt-PT": "SWOT + Persona",                "en": "SWOT + Persona",            "fr": "SWOT + Persona",            "tn": "SWOT + Persona",            "ar": "SWOT + بيرسونا"},
    "walk.audio.problem.title": {"pt-PT": "Secções 2 + 3",                "en": "Sections 2 + 3",            "fr": "Sections 2 + 3",            "tn": "Sections 2 + 3",            "ar": "الأقسام ٢ + ٣"},
    "walk.audio.problem.label": {"pt-PT": "Persona + Marketing Problem",   "en": "Persona + Marketing Problem", "fr": "Persona + Problème marketing", "tn": "Persona + Problème marketing", "ar": "بيرسونا + مشكلة التسويق"},
    "walk.audio.tows.title":    {"pt-PT": "Secções 4 + 5",                "en": "Sections 4 + 5",            "fr": "Sections 4 + 5",            "tn": "Sections 4 + 5",            "ar": "الأقسام ٤ + ٥"},
    "walk.audio.tows.label":    {"pt-PT": "TOWS + Recommendation",         "en": "TOWS + Recommendation",     "fr": "TOWS + Recommandation",     "tn": "TOWS + Recommandation",     "ar": "TOWS + التوصية"},
}

total_added = 0
for lang in ["pt-PT", "en", "fr", "tn", "ar"]:
    fp = i18n_dir / f"{lang}.json"
    d = json.loads(fp.read_text(encoding="utf-8"))
    added = 0
    for k, translations in new_keys.items():
        if k not in d:
            d[k] = translations[lang]
            added += 1
    fp.write_text(json.dumps(d, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    total_added += added
    print(f"{lang}.json: +{added} keys (total {len(d)})")

print(f"TOTAL added: {total_added}")
print(f"NEW keys defined: {len(new_keys)}")
